name: dev ci build
on:
  pull_request:
    types: [opened, reopened, review_requested] # test용도로 review_requested 셋팅
    branches:
      - "develop"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: CI start send message
        uses: jabiseo/slack-custom-bot@main
        with:
          mode: PR
          channelId: "${{ secrets.NOTI_CHANNEL_ID }}"
          text: "PullRequest 요청"
          statusColor: "#ebe834"
        env:
          SLACK_TOKNE: "${{ secrets.SLACK_BOT_TOKEN }}"

      - name: setup environment
        env:
          DEV_VARIABLES: ${{ toJson(secrets) }}
        run: |
          echo "$DEV_VARIABLES" | jq -r 'to_entries | 
          map(select(.key | startswith("DEV_NEXT_PUBLIC_")))[] | "\(.key | sub("^DEV_"; ""))=\(.value)"' > .env

      - name: set up yarn
        run: npm i -g yarn

      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
          cache: yarn

      - run: yarn install --frozen-lockfile

      - name: yarn build
        run: yarn run build
